FROM node:18-slim

RUN apt-get update && apt-get install -y postgresql-client && rm -rf /var/lib/apt/lists/*
RUN npm install -g graphile-migrate

# Default working directory. Map your migrations folder in here with `docker -v`
WORKDIR /app

COPY . .

# ENTRYPOINT ["/usr/local/bin/graphile-migrate"]
CMD graphile-migrate migrate
