version: '3.5'

services:
  streamlit:
    build:
      dockerfile: Dockerfile
    ports:
      - "8501:8501"
    volumes:
      - streamlit:/data/streamlit
      - ./:/app
      - ./data:/app/data
    env_file: .env

volumes:
  streamlit:
